### ISSUE TITLE
APIAI session id

### ISSUE THREAD

**Issue by slidenerd** [GanadiniAkshay/airfi#1]
First of all, thank you for the hardwork behind the insanely famous bot airfi 👍 I was wondering if you saw this. You have used the library api-ai-recognizer and it has this sentence on line 12 in its lib
var request = this.app.textRequest(context.message.text.toLowerCase(),{sessionId: 'kjfgwsjhedfcb281908'});

Basically the session Id seems to be a literal value. Isnt that unique for each session and user?
Let me know your thoughts on this

**Comment by GanadiniAkshay** [comment]
this is actually a bug on the api.ai recognizer closing this and opening bug there

you can track it here:
https://github.com/GanadiniAkshay/ApiAiRecognizer/issues/2
